/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  map?: string
}
export function sum(a: number, b: number): number
export class Parser {
  constructor()
  parse(file: string, shouldResolve: boolean): void
}
