/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  map?: string
}
export class Parser {
  constructor(root?: Buffer | undefined | null)
  parse(file: Buffer, shouldResolve: boolean): Buffer
}
